name: Build VuePress
on: [push]
jobs:
  build-and-deploy:
    runs-on: linux-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build HTML File
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: CraftStarStudio/lwjglbook-bookcontents-zh_CN
        TARGET_BRANCH: pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: .vuepress/dist/
